### ISSUE TITLE
v1.0.0-beta doesn't work

### ISSUE THREAD

**Issue by angelbt91** [angelbt91/ff-pixel-helper#13]
Thread to follow @jacobshare's feedback about issues on testing a local copy of v1.0.0-beta (following #3 )

**Comment by jacobshare** [comment]
Hey
I tried downloading the code again and installing as a temporary addon, and then visiting theverge.com in a new tab. When I do that, the ff dropdown is empty as in my previous screenshot. Here's the console:

![StrokesPlus_PNegq9mjcM](https://user-images.githubusercontent.com/6898100/97102169-08a2b900-16ac-11eb-8dc2-b5ac1ed85e4c.png)

However, now that there's a release, I'll remove this and try that instead.

**Comment by angelbt91** [comment]
Great, let's follow at #15. Thanks!
