### ISSUE TITLE
Add pixel counter on popup's icon

### ISSUE THREAD

**Issue by angelbt91** [angelbt91/ff-pixel-helper#17]
Suggested by @jacobshare [here](https://github.com/angelbt91/ff-pixel-helper/issues/15#issuecomment-716356754).

**Comment by angelbt91** [comment]
@jacobshare it's live! I guess you will receive a notification soon to update ff. Let me know if you encounter any bug or problem with the popup icon badge :)

**Comment by jacobshare** [comment]
Cool! Works great. I can literally stop using Chrome now. Fantastic!

**Comment by angelbt91** [comment]
That sounds great! I think I will be able to stop using Chrome now too :) Happy to help.

If you like the extension, feel free to spread the word to whoever may be interested! And if you think it deserves it, you can contribute (even more) by rating FF on the [Add-on Store](https://addons.mozilla.org/en-US/firefox/addon/ff-pixel-helper/), or starring this GitHub repo. Of course, do it only if you feel like doing it :)

Thanks for all!
