### ISSUE TITLE
Add documentation for both users and developers in README.md

### ISSUE THREAD

**Issue by angelbt91** [angelbt91/ff-pixel-helper#3]

**Comment by jacobshare** [comment]
Really excited to hear about this, it's one of the only reasons I still have Chrome installed.

Could the docs explain how to build the extension for Firefox on Windows?

**Comment by angelbt91** [comment]
Hi Jacob!

I'm really excited also, as you are the first person showing interest in the extension :) Your comment made my day, thanks!

Original Facebook's Pixel Helper is also the only reason I use Chrome, that's why I started building this. Be aware though, that I can't guarantee that this plugin is going to work as fine as the original, and will probably have some limitations. So far, the results are good, but I still have to test it on more websites and situations. If you are willing to use this plugin, any feedback or bug report is welcome!  

Anyway, right to your question! I'm thinking on three ways of having it on Windows:
- Right now, you can install [Nodejs and npm](https://nodejs.org/en/) on Windows and follow the instructions on the [readme](https://github.com/angelbt91/ff-pixel-helper/blob/master/README.md). Then, you can run the extension as a temporary by writing `about:debugging` in the address bar, clicking on "This Firefox", then on "Load Temporary Add-on..." and opening any file from the extension folder.
- As soon as I fix the remaining open issue (#6), I will send the extension to Firefox's addon library. I'm not 100% sure it will get approved, because of the usage of Facebook's logo and name, but I will hope for the best and do everything I can to publish it.
- In any case, when #6 it's solved, I'll also get the extension signed and publish it on the [releases](https://github.com/angelbt91/ff-pixel-helper/releases) section, so anybody will be able to download and install it.

Let me know how you want to proceed, in case I can help you with anything.

**Comment by jacobshare** [comment]
Cool 👍 

I installed Nodejs and npm without a problem, but the browserify command throws this:

`C:\Users\xxxxx>browserify background-pre.js -o background.js
Error: Can't walk dependency graph: Cannot find module 'C:\Users\xxxxx\background-pre.js' from 'C:\Users\xxxxx\_fake.js'
    required by C:\Users\xxxxx\_fake.js
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:136:35
    at load (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:155:43)
    at onex (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:180:17)
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:15:69
    at FSReqCallback.oncomplete (fs.js:168:21)`

**Comment by angelbt91** [comment]
Make sure to run the `browserify` command inside the extension folder. From your error message, it looks like you are running the command while at the folder `C:\Users\xxxxx`.

It should work right if first you navigate in the terminal to the extension folder, by using the command `cd <folder-name>`. Also, the `dir` command may come handy for navigating to the extension folder, as it lists the files inside the current folder, so you can check where you are and how the next folder in the route is named.

Let me know if you need more help. And, if you get it running, any feedback - good or bad - is welcome! :)

**Comment by jacobshare** [comment]
> Make sure to run the `browserify` command inside the extension folder

Which extension folder and how can I easily find it?

I thought you may have meant my Firefox profile's extensions folder, which was a pain to find in AppData\Roaming\Mozilla\etc.., but I get the same error there

**Comment by angelbt91** [comment]
Oh sorry, I meant the folder of this project. Did you download it? You can download it from the main page of the project [here in Github](https://github.com/angelbt91/ff-pixel-helper), or directly [here](https://github.com/angelbt91/ff-pixel-helper/archive/master.zip).

**Comment by jacobshare** [comment]
I did now! Silly me. But it's still having an issue finding stuff:

`C:\Users\xxxxx\AppData\Roaming\Mozilla\Firefox\Profiles\dev-edition-default\extensions\ff-pixel-helper-master>browserify background-pre.js -o background.js
Error: Can't walk dependency graph: Cannot find module 'query-string' from 'C:\Users\xxxxx\AppData\Roaming\Mozilla\Firefox\Profiles\dev-edition-default\extensions\ff-pixel-helper-master\background-pre.js'
    required by C:\Users\xxxxx\AppData\Roaming\Mozilla\Firefox\Profiles\dev-edition-default\extensions\ff-pixel-helper-master\background-pre.js
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:115:35
    at processDirs (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:268:39)
    at isdir (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:275:32)
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:25:69
    at FSReqCallback.oncomplete (fs.js:168:21)`

**Comment by angelbt91** [comment]
I think you are probably missing the 'npm install` inside the folder before the `browserify` command.

Anyway, I went ahead and packed a beta version of the extension, so you can avoid doing these deployment steps :)

Just [download this zip](https://github.com/angelbt91/ff-pixel-helper/releases/download/v1.0.0-beta/ff-pixel-helper-1.0.0-beta.zip) and unzip it wherever you wish, no need to put it inside Firefox's Roaming folder.

Then, open Firefox, write `about:debugging` in the address bar, click on "This Firefox", then on "Load Temporary Add-on..." and open any file from the folder you downloaded, like `manifest.json` for example. Now, the plugin should be available for you to use, until you close the browser. Repeat the steps from this paragraph to enable it again.

In order to make the plugin permanent, that is, not disappearing after every browser exit, I still have to:
- Get the plugin signed by Mozilla.
- And, ideally, get the plugin published in the Addon Library.

I'll keep you updated whenever I complete these last steps. In the meantime, any feedback is welcome :)

Thank you very much!

**Comment by jacobshare** [comment]
Great.

I activated the plugin via about:debugging and the 'ff' button immediately appeared in my toolbar. However, when I visit sites that have the facebook pixel (such as [my site](https://jobmob.co.il/) or [The Verge](https://www.theverge.com/)), the ff button doesn't change and clicking it gets the dropdown saying 'Nothing to show'.

Is it supposed to work exactly like the Chrome version?

**Comment by angelbt91** [comment]
Hi!

Great that you got it running, and thanks for the feedback.

I tried it myself on these two pages and it's working for me (check attached screenshots).

Make sure that:
- You accepted cookies in the pages you visit. Some sites don't enable firing Facebook events until they get consent from the user. Reload after accepting cookies.
- After loading a temporary plugin, you need to reload the pages that you already had open to fire again the events and make them appear on the popup. This won't be necessary when the plugin is installed in the "proper" way, as the plugin will launch when the browser boots.

(By the way, someone has to tell The Verge that their pixel implementation is quite old :) )

![JobMob](https://user-images.githubusercontent.com/56364209/96996064-81303b00-152f-11eb-8479-8f2da5016192.png)
![TheVerge](https://user-images.githubusercontent.com/56364209/96996067-81c8d180-152f-11eb-892b-4b27b6487694.png)

**Comment by jacobshare** [comment]
Still no good for me.

Now I'm not even seeing 'Nothing to show', I just get a tiny, empty popup. Ffx was already accepting, and you can see that I even disabled Enhanced Tracking Protection:

![Screenshot 2020-10-23 145124](https://user-images.githubusercontent.com/6898100/97000360-4d5d1180-153f-11eb-9737-13b66d96e8ef.png)

**Comment by angelbt91** [comment]
Hi Jacob!

So weird, let me investigate it. I will try to reproduce your behavior on other Windows computers in order find a solution.

In the meantime, would you send me an screenshot of the logs in the extension's console? You can find the console if you click on "Inspect" (screenshot 1) and then, in the tab that opens, on "Console" (screenshot 2). Make sure to first browse some websites while opening the popup ocasionally, so if there's any error with the extension it will be appearing in the console.

Thanks for your help, much appreciated!

![1](https://user-images.githubusercontent.com/56364209/97021281-ef3a2980-1552-11eb-8a0e-affd8ec527be.png)
![2](https://user-images.githubusercontent.com/56364209/97021284-efd2c000-1552-11eb-88dc-d88301f444b1.png)

**Comment by angelbt91** [comment]
I closed this issue as I already finished adding the documentation. However, I made a separate issue for your case. Let's keep speaking at #13 :)

**Comment by angelbt91** [comment]
[It's live](https://addons.mozilla.org/en-US/firefox/addon/ff-pixel-helper/)! :)

Let me know if now works for you.

**Comment by jacobshare** [comment]
Congrats!

Just installed it. I'll open another bug if necessary
